data_cfg:
  data_dir: /projects/u6bk/wanli/ensemble_dataset # Path to ensemble data root
  preprocessed_dir: ${data_cfg.data_dir}/preprocessed_data
  batch_size: 10  # 28
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  drop_last: false
  val_ensemble_as_cluster: true
  test_ensemble_as_cluster: true
  max_seq_len: 300

interpolant:
  min_t: 1e-2
  rots:
    sample_schedule: exp
    exp_rate: 10
  sampling:
    num_timesteps: 60
  self_condition: ${model.edge_features.self_condition}

model:
  node_embed_size: 256
  edge_embed_size: 128
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    c_single_in: 384
  edge_features:
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    c_pair_in: 128
    feat_dim: 64
    num_bins: 22
    self_condition: True
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 5   # 6

experiment:
  seed: 123
  training:
    loss: se3_vf_loss
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.25
    tors_loss_scale: 1.0
    num_non_frame_atoms: 0 # choose from [0, 3, 7]
  validation:
    num_generated: 50
  wandb:
    name: baseline
    project: ens_flow
    save_code: false
    tags: []
    mode: "online" # can also save to `offline`
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    # max_steps: 120000
    # min_steps: 1
    min_epochs: 1
    max_epochs: 1000
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp_find_unused_parameters_true
    check_val_every_n_epoch: 10
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: /projects/u6bk/wanli/ckpt_flow/${experiment.wandb.project}/${experiment.wandb.name}/

fk_flow:
  enabled: true
  amplitude_net:
    c_single_in: ${model.node_features.c_single_in}  # 384
    timestep_embed_dim: 64
    hidden_dim: 128
    num_layers: 4
    kernel_size: 5
  uncertainty_net:
    c_single_in: ${model.node_features.c_single_in}  # 384
    timestep_embed_dim: 64
    hidden_dim: 128
    num_layers: 4
    kernel_size: 5
  loss:
    td_weight: 1.0
    term_weight: 1.0
    init_weight: 1.0
  optimizer:
    lr: 0.0003
  drift_lr_scale: 0.1
