# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - config
  - _self_

inference:
  run_inference: True
  seed: 123
  ckpt_path: /projects/u6bk/wanli/checkpoint/rnafm_ckpt/ensemble_flow_matching/last.ckpt
  output_dir: /projects/u6bk/wanli/inference/rnafm_ensemble
  test_clusters_json: /projects/u6bk/wanli/inference/test_clusters.json
  test_cluster_split: test_ensemble  # all|both|test_single|single|test_ensemble|ensemble
  
  ensemble:
    enabled: true
    num_generated: 200  # 每个簇采样200个结构

  num_gpus: 4

  ens_flow:
    num_z_samples: 5

  interpolant:
    min_t: 1e-2
    rots:
      corrupt: True
      sample_schedule: exp
      exp_rate: 10
    trans:
      corrupt: True
      sample_schedule: linear
    sampling:
      num_timesteps: 50
    self_condition: True
